# Generated by Django 3.1.4 on 2020-12-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ID',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
